# Generated by Django 5.1.2 on 2024-11-21 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sharedlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedlink',
            old_name='thread_id',
            new_name='assistant_id',
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='main.project'),
            preserve_default=False,
        ),
    ]
