# Generated by Django 5.1.2 on 2024-12-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_key_project_unique_key_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='project',
        ),
        migrations.AddField(
            model_name='thread',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
