# Generated by Django 5.1.2 on 2024-12-12 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_thread_project_thread_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['openai_id'], name='openai_id_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['created_at'], name='created_at_idx'),
        ),
    ]
