# Generated by Django 5.1.1 on 2024-09-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cloud_service_keys",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(name="CloudStorageKey",),
    ]
