# Generated by Django 5.1.1 on 2024-09-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_cloud_service_keys_delete_cloudstoragekey"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription",
            field=models.CharField(
                choices=[("f", "Free"), ("p", "Pro"), ("e", "Enterprise")],
                default="f",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cloud_service_keys",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
