# Generated by Django 5.1.1 on 2025-02-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_project'),
        ('main', '0012_sharedlink_user_thread_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
