# Generated by Django 5.1.2 on 2025-02-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_alter_folder_project'),
        ('main', '0012_sharedlink_user_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldervectorstore',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='project',
        ),
        migrations.AddField(
            model_name='folder',
            name='projects',
            field=models.ManyToManyField(blank=True, to='main.project'),
        ),
        migrations.AddField(
            model_name='folder',
            name='sync_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FolderAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder')),
            ],
        ),
        migrations.DeleteModel(
            name='FolderSync',
        ),
        migrations.DeleteModel(
            name='FolderVectorStore',
        ),
    ]
