# Generated by Django 5.1.2 on 2025-02-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_remove_foldervectorstore_folder_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folderassistant',
            unique_together={('folder', 'assistant_id')},
        ),
    ]
