# Generated by Django 5.1.1 on 2025-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0006_alter_folderassistant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='file_ids',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='FolderFile',
        ),
    ]
