# Generated by Django 5.1.1 on 2025-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0008_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='file_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
