# Generated by Django 5.1.2 on 2025-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0009_alter_folder_file_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='folder',
            name='sync_source',
        ),
    ]
