# Generated by Django 5.1.1 on 2025-01-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0012_sharedlink_user_thread_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAPIFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('argument_schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAPIFunction',
            fields=[
                ('baseapifunction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='function_calls.baseapifunction')),
                ('endpoint', models.URLField(blank=True, null=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('bearer_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('function_calls.baseapifunction',),
        ),
        migrations.CreateModel(
            name='FunctionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=50)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status_code', models.CharField(blank=True, max_length=5, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='function_calls.baseapifunction')),
            ],
        ),
        migrations.CreateModel(
            name='LocalAPIFunction',
            fields=[
                ('baseapifunction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='function_calls.baseapifunction')),
                ('code', models.TextField(blank=True, default='')),
                ('extra_context', models.JSONField(blank=True, default=dict)),
                ('template', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assistant_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            bases=('function_calls.baseapifunction',),
        ),
    ]
