# Generated by Django 5.1.1 on 2025-01-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('endpoint', models.URLField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('bearer_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('s', 'string'), ('i', 'integer'), ('o', 'object')], max_length=1)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='function_calls.function')),
            ],
        ),
    ]
