# Generated by Django 5.1.1 on 2025-01-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localapifunction',
            name='template',
        ),
        migrations.AddField(
            model_name='localapifunction',
            name='result_template',
            field=models.TextField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='localapifunction',
            name='result_type',
            field=models.CharField(default='application/json', max_length=100),
        ),
    ]
