# Generated by Django 5.1.1 on 2025-01-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='endpoint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('o', 'object'), ('s', 'string'), ('n', 'number'), ('b', 'boolean'), ('-', 'null')], max_length=1),
        ),
    ]
