# Generated by Django 5.1.1 on 2025-01-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0002_alter_function_endpoint_alter_parameter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='slug',
            field=models.SlugField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
