# Generated by Django 5.1.2 on 2025-01-31 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0002_remove_localapifunction_template_and_more'),
        ('main', '0012_sharedlink_user_thread_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeInterpreterScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(db_index=True, max_length=50)),
                ('thread_id', models.CharField(db_index=True, max_length=50)),
                ('run_id', models.CharField(db_index=True, max_length=50)),
                ('run_step_id', models.CharField(db_index=True, max_length=50)),
                ('tool_call_id', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet_index', models.PositiveIntegerField(default=1)),
                ('code', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
