# Generated by Django 5.1.1 on 2025-02-06 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0003_codeinterpreterscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseapifunction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
