# Generated by Django 5.1.2 on 2025-02-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0003_codeinterpreterscript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionexecution',
            name='function_name',
        ),
        migrations.AlterField(
            model_name='functionexecution',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='function_calls.baseapifunction'),
        ),
    ]
