# Generated by Django 5.1.2 on 2025-02-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0004_remove_functionexecution_function_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionexecution',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
