# Generated by Django 5.1.1 on 2025-01-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0004_externalapifunction_alter_parameter_type_and_more'),
        ('main', '0012_sharedlink_user_thread_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfunction',
            name='assistant_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='localfunction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
