# Generated by Django 5.1.2 on 2025-02-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0004_baseapifunction_uuid'),
        ('main', '0012_sharedlink_user_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionexecution',
            name='function_name',
        ),
        migrations.RemoveField(
            model_name='localapifunction',
            name='project',
        ),
        migrations.AddField(
            model_name='baseapifunction',
            name='projects',
            field=models.ManyToManyField(blank=True, to='main.project'),
        ),
        migrations.AddField(
            model_name='functionexecution',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_executions', to='main.thread'),
        ),
        migrations.AlterField(
            model_name='functionexecution',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='function_calls.baseapifunction'),
        ),
        migrations.AlterField(
            model_name='functionexecution',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
