# Generated by Django 5.1.2 on 2025-02-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0005_alter_functionexecution_time'),
        ('main', '0012_sharedlink_user_thread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionexecution',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_executions', to='main.thread'),
        ),
    ]
