# Generated by Django 5.1.1 on 2025-01-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0005_alter_localfunction_assistant_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localfunction',
            old_name='properties',
            new_name='parameters',
        ),
    ]
