# Generated by Django 5.1.2 on 2025-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0005_remove_functionexecution_function_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionexecution',
            name='executed_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
