# Generated by Django 5.1.1 on 2025-01-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0006_rename_properties_localfunction_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfunction',
            name='returns',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
