# Generated by Django 5.1.2 on 2025-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0006_functionexecution_executed_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localapifunction',
            name='assistant_id',
        ),
        migrations.AddField(
            model_name='baseapifunction',
            name='assistant_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
