# Generated by Django 5.1.2 on 2025-01-29 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0007_alter_localfunction_returns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeinterpreterscript',
            name='code',
        ),
        migrations.AddField(
            model_name='codeinterpreterscript',
            name='run_id',
            field=models.CharField(db_index=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CodeInterpreterSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_step_id', models.CharField(db_index=True, max_length=50)),
                ('tool_call_id', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet_index', models.PositiveIntegerField(default=1)),
                ('code_block', models.TextField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='function_calls.codeinterpreterscript')),
            ],
        ),
    ]
