# Generated by Django 5.1.2 on 2025-01-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0008_remove_codeinterpreterscript_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeinterpreterscript',
            name='code',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeinterpreterscript',
            name='run_step_id',
            field=models.CharField(db_index=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeinterpreterscript',
            name='snippet_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='codeinterpreterscript',
            name='tool_call_id',
            field=models.CharField(db_index=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CodeInterpreterSnippet',
        ),
    ]
