# Generated by Django 5.1.2 on 2025-03-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_calls', '0008_baseapifunction_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseapifunction',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
