name: Deploy to Server

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set deployment directory
        id: vars
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            echo "DEPLOY_DIR=OpenAssistants-dev" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "main" ]; then
            echo "DEPLOY_DIR=OpenAssistants-main" >> $GITHUB_ENV
          fi

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to Server
        env:
          DEPLOY_DIR: ${{ env.DEPLOY_DIR }}
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@3.87.35.129 <<EOF
            cd /home/ubuntu/$DEPLOY_DIR
            git fetch origin
            git reset --hard origin/${{ github.ref_name }}
            # Additional commands for Django:
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn  # Replace with your WSGI server
          EOF